export declare const b__NODE_ENV: (ctx?: any, opts?: any) => import("svelte/store").Writable<string>;
export declare const __NODE_ENV: import("svelte/store").Writable<string>;
export declare const b__CACHE_VERSION: (ctx?: any, opts?: any) => import("svelte/store").Writable<string>;
export declare const __CACHE_VERSION: import("svelte/store").Writable<string>;
export declare const b__VERSION: (ctx?: any, opts?: any) => import("svelte/store").Writable<string | number>;
export declare const __VERSION: import("svelte/store").Writable<string | number>;
export declare const b__is__production: (ctx?: any, opts?: any) => import("svelte/store").Readable<boolean>;
export declare const __is__production: import("svelte/store").Readable<boolean>;
export declare const b__is__staging: (ctx?: any, opts?: any) => import("svelte/store").Readable<boolean>;
export declare const __is__staging: import("svelte/store").Readable<boolean>;
export declare const b__is__development: (ctx?: any, opts?: any) => import("svelte/store").Readable<boolean>;
export declare const __is__development: import("svelte/store").Readable<boolean>;
